name: Cloud Foundry Workflow
on:
  push:
    branches:
      - master
jobs:
  test-the-server:
    runs-on: ubuntu-latest
    steps:
      - name: Get The Repo Code
        uses: actions/checkout@v4

      - name: Install The Dependcies
        run: npm i

      - name: Cachce All Dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: natours-dependencies-${{hashFiles('**/package-lock.json')}}

      - name: Test The Server
        run: npm run test

  deploy-the-server:
    runs-on: ubuntu-latest
    needs: test-the-server
    steps:
      - name: Get The Repo Code
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: npm i

      - name: Cache All Dependencies
        uses: actions/caches@v4
        with:
          path: ~/.npm
          key: natours-dependencies-${{hashFiles('**/package-lock.json')}}

      - name: Build The Server
        run: npm run build

      - name: Login To Cloud Foundry
        uses: elliottpope/cloudfoundry-cli-action@v6
        with:
          CF_API: https://api.cf.us10-001.hana.ondemand.com/
          USERNAME: ${{secrets.CF_USERNAME}}
          PASSWORD: ${{secrets.CF_PASSWORD}}
          ORG: dd192eb7trial
          SPACE: dev
          COMMAND: push NatoursApp
