name: Cloud Foundry Workflow
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  test-the-server:
    runs-on: ubuntu-latest
    steps:
      - name: Get The Repo Code
        uses: actions/checkout@v4

      - name: Install The Dependencies
        uses: ./.github/actions/install_dependencies
        with:
          caching: "false"

      - name: Test The Server
        run: npm run test

  # test-login:
  #   uses: ./.github/workflows/cloud_foundry.yml
  #   secrets:
  #     USERNAME: ${{secrets.CF_USERNAME}}
  #     PASSWORD: ${{secrets.CF_PASSWORD}}
  #     API_ENDPOINT: https://api.cf.us10-001.hana.ondemand.com/

  deploy-the-server:
    runs-on: ubuntu-latest
    needs: test-the-server
    steps:
      - name: Get The Repo Code
        uses: actions/checkout@v4

      - name: Install The Dependencies
        uses: ./.github/actions/install_dependencies
        id: dependency-installation
        with:
          caching: "false"

      - name: Output Caching State
        run: echo "The Used Caching State is ${{steps.dependency-installation.outputs.used-cache}}"

      - name: Build The Server
        run: npm run build

      - name: Login To Cloud Foundry
        uses: elliottpope/cloudfoundry-cli-action@v6
        with:
          CF_API: https://api.cf.us10-001.hana.ondemand.com/
          USERNAME: ${{secrets.CF_USERNAME}}
          PASSWORD: ${{secrets.CF_PASSWORD}}
          ORG: dd192eb7trial
          SPACE: dev
          COMMAND: push NatoursApp
